services:
  test:
    image: dejwcake/php8.5:1
    volumes:
      - .:/var/www/html:delegated

  php-qa:
    image: dejwcake/phpqa8.5:1
    volumes:
      - .:/var/www/html:delegated

networks:
  default:
    name: testing-kit
